ignorePatterns: ["/**", "!/src", "!/test"]

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  complexity: [error, max: 5]
  max-depth: [error, max: 2]
  max-nested-callbacks: [error, max: 2]
  max-params: [error, max: 3]
  max-statements: [error, 10, ignoreTopLevelFunctions: false]
  max-len: [error, code: 120]
  max-lines: [error, {max: 200, skipComments: true, skipBlankLines: true}]
  semi: [error, always]
  space-before-function-paren: [error, {anonymous: always, named: never, asyncArrow: always}]

  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
